[project]
name = "selenium-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask-cors>=5.0.1",
    "flask>=3.1.0",
    "numpy>=2.2.3",
    "selenium>=4.29.0",
    "webdriver-manager>=4.0.2",
]
